2024-02-07T04:13:28.796Z:	"Error: ER_BAD_FIELD_ERROR: Unknown column 'user_id' in 'field list'\n    at Sequence._packetToError (D:\\Node\\test\\node_modules\\mysql\\lib\\protocol\\sequences\\Sequence.js:47:14)\n    at Query.ErrorPacket (D:\\Node\\test\\node_modules\\mysql\\lib\\protocol\\sequences\\Query.js:79:18)\n    at Protocol._parsePacket (D:\\Node\\test\\node_modules\\mysql\\lib\\protocol\\Protocol.js:291:23)\n    at Parser._parsePacket (D:\\Node\\test\\node_modules\\mysql\\lib\\protocol\\Parser.js:433:10)\n    at Parser.write (D:\\Node\\test\\node_modules\\mysql\\lib\\protocol\\Parser.js:43:10)\n    at Protocol.write (D:\\Node\\test\\node_modules\\mysql\\lib\\protocol\\Protocol.js:38:16)\n    at Socket.<anonymous> (D:\\Node\\test\\node_modules\\mysql\\lib\\Connection.js:88:28)\n    at Socket.<anonymous> (D:\\Node\\test\\node_modules\\mysql\\lib\\Connection.js:526:10)\n    at Socket.emit (node:events:514:28)\n    at addChunk (node:internal/streams/readable:376:12)\n    --------------------\n    at Protocol._enqueue (D:\\Node\\test\\node_modules\\mysql\\lib\\protocol\\Protocol.js:144:48)\n    at Connection.query (D:\\Node\\test\\node_modules\\mysql\\lib\\Connection.js:198:25)\n    at node:internal/util:442:7\n    at new Promise (<anonymous>)\n    at Connection.query (node:internal/util:428:12)\n    at Object.query (D:\\Node\\test\\config\\db.js:10:10)\n    at Object.dynamicInsert (D:\\Node\\test\\services\\common.js:74:29)\n    at D:\\Node\\test\\api\\account.js:40:37\n    at D:\\Node\\test\\helpers\\catch-async.js:6:5\n    at Layer.handle [as handle_request] (D:\\Node\\test\\node_modules\\express\\lib\\router\\layer.js:95:5)"
2024-02-07T04:14:06.238Z:	"Error: ER_BAD_FIELD_ERROR: Unknown column 'user_id' in 'field list'\n    at Sequence._packetToError (D:\\Node\\test\\node_modules\\mysql\\lib\\protocol\\sequences\\Sequence.js:47:14)\n    at Query.ErrorPacket (D:\\Node\\test\\node_modules\\mysql\\lib\\protocol\\sequences\\Query.js:79:18)\n    at Protocol._parsePacket (D:\\Node\\test\\node_modules\\mysql\\lib\\protocol\\Protocol.js:291:23)\n    at Parser._parsePacket (D:\\Node\\test\\node_modules\\mysql\\lib\\protocol\\Parser.js:433:10)\n    at Parser.write (D:\\Node\\test\\node_modules\\mysql\\lib\\protocol\\Parser.js:43:10)\n    at Protocol.write (D:\\Node\\test\\node_modules\\mysql\\lib\\protocol\\Protocol.js:38:16)\n    at Socket.<anonymous> (D:\\Node\\test\\node_modules\\mysql\\lib\\Connection.js:88:28)\n    at Socket.<anonymous> (D:\\Node\\test\\node_modules\\mysql\\lib\\Connection.js:526:10)\n    at Socket.emit (node:events:514:28)\n    at addChunk (node:internal/streams/readable:376:12)\n    --------------------\n    at Protocol._enqueue (D:\\Node\\test\\node_modules\\mysql\\lib\\protocol\\Protocol.js:144:48)\n    at Connection.query (D:\\Node\\test\\node_modules\\mysql\\lib\\Connection.js:198:25)\n    at node:internal/util:442:7\n    at new Promise (<anonymous>)\n    at Connection.query (node:internal/util:428:12)\n    at Object.query (D:\\Node\\test\\config\\db.js:10:10)\n    at Object.dynamicInsert (D:\\Node\\test\\services\\common.js:74:29)\n    at D:\\Node\\test\\api\\account.js:40:37\n    at D:\\Node\\test\\helpers\\catch-async.js:6:5\n    at Layer.handle [as handle_request] (D:\\Node\\test\\node_modules\\express\\lib\\router\\layer.js:95:5)"
2024-02-07T04:14:10.764Z:	"Error: ER_BAD_FIELD_ERROR: Unknown column 'user_id' in 'field list'\n    at Sequence._packetToError (D:\\Node\\test\\node_modules\\mysql\\lib\\protocol\\sequences\\Sequence.js:47:14)\n    at Query.ErrorPacket (D:\\Node\\test\\node_modules\\mysql\\lib\\protocol\\sequences\\Query.js:79:18)\n    at Protocol._parsePacket (D:\\Node\\test\\node_modules\\mysql\\lib\\protocol\\Protocol.js:291:23)\n    at Parser._parsePacket (D:\\Node\\test\\node_modules\\mysql\\lib\\protocol\\Parser.js:433:10)\n    at Parser.write (D:\\Node\\test\\node_modules\\mysql\\lib\\protocol\\Parser.js:43:10)\n    at Protocol.write (D:\\Node\\test\\node_modules\\mysql\\lib\\protocol\\Protocol.js:38:16)\n    at Socket.<anonymous> (D:\\Node\\test\\node_modules\\mysql\\lib\\Connection.js:88:28)\n    at Socket.<anonymous> (D:\\Node\\test\\node_modules\\mysql\\lib\\Connection.js:526:10)\n    at Socket.emit (node:events:514:28)\n    at addChunk (node:internal/streams/readable:376:12)\n    --------------------\n    at Protocol._enqueue (D:\\Node\\test\\node_modules\\mysql\\lib\\protocol\\Protocol.js:144:48)\n    at Connection.query (D:\\Node\\test\\node_modules\\mysql\\lib\\Connection.js:198:25)\n    at node:internal/util:442:7\n    at new Promise (<anonymous>)\n    at Connection.query (node:internal/util:428:12)\n    at Object.query (D:\\Node\\test\\config\\db.js:10:10)\n    at Object.dynamicInsert (D:\\Node\\test\\services\\common.js:74:29)\n    at D:\\Node\\test\\api\\account.js:40:37\n    at D:\\Node\\test\\helpers\\catch-async.js:6:5\n    at Layer.handle [as handle_request] (D:\\Node\\test\\node_modules\\express\\lib\\router\\layer.js:95:5)"
2024-02-07T05:04:48.480Z:	undefined
